# .rubocop.yml

# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Regras personalizadas adicionais
Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

# Regras básicas de estilo
Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/IndentationWidth:
  Width: 2

Layout/SpaceAroundOperators:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false

# Arquivos a serem ignorados
AllCops: Exc
