default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: zxc123
  host: localhost

development:
  <<: *default
  database: mindrails_development

test:
  <<: *default
  database: mindrails_test

production:
  <<: *default
  database: mindrails_production
  username: mindrails
  password: <%= ENV["MINDRAILS_DATABASE_PASSWORD"] %>
